apiVersion: v1
kind: Secret
metadata:
  name: shared-secrets
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: ''
  SPRING_DATASOURCE_PASSWORD: ''
  GOOGLE_CLIENT_ID: ''
  GOOGLE_CLIENT_SECRET: ''
  JWT_SECRET: ''