apiVersion: v1
kind: Service
metadata:
  name: borsibaar-frontend
spec:
  selector:
    app: borsibaar-frontend
  ports:
    - protocol: 'TCP'
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: borsibaar-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: borsibaar-frontend
  template:
    metadata:
      labels:
        app: borsibaar-frontend
    spec:
      containers:
        - name: borsibaar-frontend
          image: {{ .Values.borsibaarFrontend.image }}:{{ .Chart.AppVersion }}
          ports:
            - containerPort: 3000
          env:
            - name: BACKEND_URL
              value: "http://borsibaar-service:8080"