apiVersion: v1
kind: Service
metadata:
  name: borsibaar-service
spec:
  selector:
    app: borsibaar-service
  ports:
    - protocol: 'TCP'
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: borsibaar-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: borsibaar-service
  template:
    metadata:
      labels:
        app: borsibaar-service
    spec:
      containers:
        - name: borsibaar-service
          image: {{ .Values.borsibaarService.image }}
          tag: "{{ .Chart.AppVersion }}"
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.borsibaarService.datasourceHost }}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: GOOGLE_CLIENT_SECRET
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: JWT_SECRET
            - name: APP_CORS_ALLOWED_ORIGINS
              value: "http://borsibaar.com"
            - name: APP_FRONTEND_URL
              value: "http://borsibaar.com"
            - name: OAUTH2_REDIRECT_URI
              value: "https://borsibaar.com/login/oauth2/code/google"
