apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
spec:
  ingressClassName: traefik
  rules:
    - host: borsibaar.com
      http:
        paths:
          - path: /api/backend
            pathType: Prefix
            backend:
              service:
                name: borsibaar-frontend
                port:
                  number: 3000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: borsibaar-service
                port:
                  number: 8080
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: borsibaar-service
                port:
                  number: 8080
          - path: /login/oauth2
            pathType: Prefix
            backend:
              service:
                name: borsibaar-service
                port:
                  number: 8080
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: borsibaar-service
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: borsibaar-frontend
                port:
                  number: 3000